config/routes.rb
Hasilsda::Application.routes.draw do
  devise_for :users

  resources :payments

  resources :bergains

  resources :orders

  resources :posts

  resources :users

  namespace :admin do
    resources :dashboards, :only => [:index]
    resources :users
    resources :payments
  end

  namespace :seller do
    resources :dashboards
    resources :posts
    resources :bergains
    resources :orders
  end

  namespace :wholeseller do
    resources :dashboards
    resources :posts do
      collection do
        get :berganing_product_price
        get :finish_transaction
        get :finish_bergaining
        get :my_post
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  namespace :buyer do
    resources :dashboards
    resources :posts do
      collection do
        get :finish_transaction
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  resources :home do
    collection do
      get :search
      get :about
    end
  end

  root :to => 'home#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  STATUS_PAYMENTS = ["In-progress", "In-checked", "Valid"]
  attr_accessible :bank_transfer_to, :date_payment, :method_payment,
    :name_owner_account, :no_rek, :no_transfer_to, :order_number, :status_payment,
    :amount
  belongs_to :order
  validates :order_number, :presence => true
  validates :date_payment, :presence => true
  validates :no_rek, :presence => true
  validates :name_owner_account, :presence => true
  validates :amount, :presence => true
  before_save :default_payment_values

  def default_payment_values
    self.status_payment ||= "new-payment"
  end

  after_save :update_total_deposit_user, :if => Proc.new { |payment| payment.status_payment == "Valid" }
  after_save :update_quantity_post, :if => Proc.new { |payment| payment.status_payment == "Valid" }
#  after_save :create_new_post_wholeseller, :if => Proc.new { |payment| payment.status_payment == "Valid" }

  # mengubah total deposit user saat payment sudah valid
  def update_total_deposit_user
    return if self.status_payment_was == "Valid"
    order = Order.find_by_order_number(self.order_number)
    return if order.nil?
    order.update_attributes(:order_status => "Valid")
    user = order.post.user
    user.update_attributes(:total_deposit => user.total_deposit.to_i + self.amount)
  end

  # mengubah total deposit user saat payment sudah valid
  def update_quantity_post
    return if self.status_payment_was == "Valid"
    order = Order.find_by_order_number(self.order_number)
    return if order.nil?
    # reduce quantity post seller
    post = order.post
    post.update_attributes(:quantity => post.quantity.to_i - order.quantity)
    return if post.post_id.present?
    # create a post wholeseller
    attributes_old_post = post.attributes.slice!("id", "created_at", "updated_at", "user_id").merge({"quantity" => 1,
        "user_id" => 1, "post_id" => post.id,
        "photo_image" => File.open("#{Rails.root}/public/#{post.photo_image_url}")
      })
    Post.create!(attributes_old_post)
  end
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"

  # GET /admin/payments
  # GET /admin/payments.json
  def index
    @payments = Payment.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /admin/payments/1
  # GET /admin/payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /admin/payments/new
  # GET /admin/payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /admin/payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /admin/payments
  # POST /admin/payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to admin_payments_url, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/payments/1
  # PUT /admin/payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to admin_payments_url, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/payments/1
  # DELETE /admin/payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to admin_payments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/buyer/payments_controller.rb
class Buyer::PaymentsController < ApplicationController
  before_filter :authenticate_user!
  layout "buyer"

  def confirm_payment
    @payment = Payment.new
  end

  def save_confirm_payment
    @payment = Payment.new(params[:payment])
    respond_to do |format|
      if @payment.save
        format.html { redirect_to buyer_dashboards_url, notice: 'Konfirmasi payment berhasil.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "confirm_payment" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/wholeseller/payments_controller.rb
class Wholeseller::PaymentsController < ApplicationController
  before_filter :authenticate_user!
  layout "wholeseller"

  def confirm_payment
    @payment = Payment.new
  end

  def save_confirm_payment
    @payment = Payment.new(params[:payment])
    respond_to do |format|
      if @payment.save
        format.html { redirect_to wholeseller_dashboards_url, notice: 'Konfirmasi payment berhasil.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "confirm_payment" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/admin/payments_helper.rb
module Admin::PaymentsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/wholeseller/payments_helper.rb
module Wholeseller::PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_rek %><br />
    <%= f.text_field :no_rek %>
  </div>
  <div class="field">
    <%= f.label :date_payment %><br />
    <%= f.date_select :date_payment %>
  </div>
  <div class="field">
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :no_transfer_to %><br />
    <%= f.text_field :no_transfer_to %>
  </div>
  <div class="field">
    <%= f.label :bank_transfer_to %><br />
    <%= f.text_field :bank_transfer_to %>
  </div>
  <div class="field">
    <%= f.label :status_payment %><br />
    <%= f.text_field :status_payment %>
  </div>
  <div class="field">
    <%= f.label :method_payment %><br />
    <%= f.text_field :method_payment %>
  </div>
  <div class="field">
    <%= f.label :name_owner_account %><br />
    <%= f.text_field :name_owner_account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>No rek</th>
    <th>Date payment</th>
    <th>Order number</th>
    <th>No transfer to</th>
    <th>Bank transfer to</th>
    <th>Status payment</th>
    <th>Method payment</th>
    <th>Name owner account</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.no_rek %></td>
    <td><%= payment.date_payment %></td>
    <td><%= payment.order_number %></td>
    <td><%= payment.no_transfer_to %></td>
    <td><%= payment.bank_transfer_to %></td>
    <td><%= payment.status_payment %></td>
    <td><%= payment.method_payment %></td>
    <td><%= payment.name_owner_account %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>No rek:</b>
  <%= @payment.no_rek %>
</p>

<p>
  <b>Date payment:</b>
  <%= @payment.date_payment %>
</p>

<p>
  <b>Order number:</b>
  <%= @payment.order_number %>
</p>

<p>
  <b>No transfer to:</b>
  <%= @payment.no_transfer_to %>
</p>

<p>
  <b>Bank transfer to:</b>
  <%= @payment.bank_transfer_to %>
</p>

<p>
  <b>Status payment:</b>
  <%= @payment.status_payment %>
</p>

<p>
  <b>Method payment:</b>
  <%= @payment.method_payment %>
</p>

<p>
  <b>Name owner account:</b>
  <%= @payment.name_owner_account %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>