config/routes.rb
Hasilsda::Application.routes.draw do
  devise_for :users

  resources :payments

  resources :bergains

  resources :orders

  resources :posts

  resources :users

  namespace :admin do
    resources :dashboards, :only => [:index]
    resources :users
    resources :payments
  end

  namespace :seller do
    resources :dashboards
    resources :posts
    resources :bergains
    resources :orders
  end

  namespace :wholeseller do
    resources :dashboards
    resources :posts do
      collection do
        get :berganing_product_price
        get :finish_transaction
        get :finish_bergaining
        get :my_post
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  namespace :buyer do
    resources :dashboards
    resources :posts do
      collection do
        get :finish_transaction
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  resources :home do
    collection do
      get :search
      get :about
    end
  end

  root :to => 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :harvest_date, :purchase_price, :quantity,
    :selling_price, :slug, :title, :user_id, :wholeseller_id, :photo_image,
    :remove_photo_image, :post_status, :photo_image_cache, :post_id
  mount_uploader :photo_image, PostImageUploader
  validates :title, :presence => true
  validates :description, :presence => true
  validates :harvest_date, :presence => true
  validate :validation_photo_image, if: "photo_image?"
  belongs_to :user
  belongs_to :wholeseller, :class_name => 'User', :foreign_key => :wholeseller_id
  has_many :orders

  def validation_photo_image
    errors[:photo_image] << "should be less than 2 Megabytes" if photo_image.size > 2.megabytes.to_i
  end
end

app/controllers/buyer/posts_controller.rb
class Buyer::PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_post, :only => [:show, :add_to_order]
  layout "buyer"

  # GET /buyer/posts
  # GET /buyer/posts.json
  def index
    @posts = Post.joins(:user).where(["posts.user_id IS NOT NULL AND users.type_user = ? AND posts.post_id IS NOT NULL", "Wholeseller"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def berganing_product_price
    @order = Order.find_by_id(session[:order_id])
    @bergain = Bergain.new
  end

  def my_post
    @posts = Post.joins(:user).where(["posts.user_id IS NOT NULL AND users.type_user = ? AND posts.post_id IS NOT NULL AND posts.user_id = ?", "buyer", current_user.id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def finish_transaction
    @order = Order.find_by_id(session[:order_id])
    session[:order_id] = nil
  end

  def finish_bergaining
    @order = Order.find_by_id(session[:order_id])
    @bergain = Bergain.find_by_id(session[:bergain_id])
    session[:order_id] = nil
    session[:bergain_id] = nil
  end

  # GET /buyer/posts/1
  # GET /buyer/posts/1.json
  def show
    @order = Order.new
    @bergain = Bergain.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

    # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to my_post_buyer_posts_path, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def find_post
    @post = Post.find_by_id(params[:id])
    if @post.nil?
      respond_to do |format|
        format.html { redirect_to seller_posts_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/seller/posts_controller.rb
class Seller::PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_post, :only => [:show, :edit, :update, :destroy]
  layout "seller"

  # GET /seller/posts
  # GET /seller/posts.json
  def index
    @posts = current_user.posts

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /seller/posts/1
  # GET /seller/posts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /seller/posts/new
  # GET /seller/posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /seller/posts/1/edit
  def edit
  end

  # POST /seller/posts
  # POST /seller/posts.json
  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to seller_posts_url, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seller/posts/1
  # PUT /seller/posts/1.json
  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to seller_posts_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seller/posts/1
  # DELETE /seller/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to seller_posts_url }
      format.json { head :no_content }
    end
  end

  private
  def find_post
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      respond_to do |format|
        format.html { redirect_to seller_posts_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/wholeseller/bergains_controller.rb
class Wholeseller::BergainsController < ApplicationController
  before_filter :authenticate_user!
  layout "wholeseller"

  # GET /wholeseller/bergains
  # GET /wholeseller/bergains.json
  def index
    @bergains = Post.find_by_sql(
      <<-SQL
        SELECT * FROM `posts`
        INNER JOIN orders ON orders.post_id = posts.id
        INNER JOIN bergains ON orders.id = bergains.order_id
        WHERE orders.user_id = #{current_user.id}
      SQL
    )
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bergains }
    end
  end

  # GET /wholeseller/bergains/1
  # GET /wholeseller/bergains/1.json
  def show
    @bergain = Bergain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bergain }
    end
  end

  # GET /wholeseller/bergains/new
  # GET /wholeseller/bergains/new.json
  def new
    @bergain = Bergain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bergain }
    end
  end

  # GET /wholeseller/bergains/1/edit
  def edit
    @bergain = Bergain.find(params[:id])
  end

  # POST /wholeseller/bergains
  # POST /wholeseller/bergains.json
  def create
    @bergain = Bergain.new(params[:bergain])

    respond_to do |format|
      if @bergain.save
        format.html { redirect_to wholeseller_bergains_url, notice: 'Bergain was successfully created.' }
        format.json { render json: @bergain, status: :created, location: @bergain }
      else
        format.html { render action: "new" }
        format.json { render json: @bergain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wholeseller/bergains/1
  # PUT /wholeseller/bergains/1.json
  def update
    @bergain = Bergain.find(params[:id])

    respond_to do |format|
      if @bergain.update_attributes(params[:bergain])
        format.html { redirect_to wholeseller_bergains_url, notice: 'Bergain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bergain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wholeseller/bergains/1
  # DELETE /wholeseller/bergains/1.json
  def destroy
    @bergain = Bergain.find(params[:id])
    @bergain.destroy

    respond_to do |format|
      format.html { redirect_to wholeseller_bergains_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/wholeseller/dashboards_controller.rb
class Wholeseller::DashboardsController < ApplicationController
  before_filter :authenticate_user!
  layout "wholeseller"

  def index
    @total_bergain = Bergain.find_by_sql(
      <<-SQL
      SELECT COUNT(orders.id) AS total_bergain_approved FROM `orders`
        INNER JOIN bergains ON bergains.order_id = orders.id
      WHERE bergains.bergain_status = "Approved" AND orders.user_id = #{current_user.id}
      SQL
    )
  end

end

app/controllers/wholeseller/orders_controller.rb
class Wholeseller::OrdersController < ApplicationController
  before_filter :authenticate_user!
  layout "wholeseller"

  # GET /wholeseller/orders
  # GET /wholeseller/orders.json
  def index
    @orders = current_user.orders

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /wholeseller/orders/1
  # GET /wholeseller/orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /wholeseller/orders/new
  # GET /wholeseller/orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /wholeseller/orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /wholeseller/orders
  # POST /wholeseller/orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to wholeseller_orders_url, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wholeseller/orders/1
  # PUT /wholeseller/orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to wholeseller_orders_url, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wholeseller/orders/1
  # DELETE /wholeseller/orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to wholeseller_orders_url }
      format.json { head :no_content }
    end
  end

  def add_order
    @order = Order.find(params[:id])
  end

  def add_to_order
    @order = Order.find(params[:id])
    @order.quantity_validate = true
    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to method_payment_wholeseller_order_url(@order), notice: 'Pemesanan sudah berhasil tambahkan.' }
        format.json { head :no_content }
      else
        format.html { render action: "add_order" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def method_payment
    @order = Order.find(params[:id])
  end

  def update_method_payment
    @order = Order.find(params[:id])
    @order.payment_method = true
    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to finish_transaction_wholeseller_order_url(@order), notice: 'Pemilihan metode payment sudah berhasil.' }
        format.json { head :no_content }
      else
        format.html { render action: "method_payment" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def finish_transaction
    @order = Order.find_by_id(params[:id])
  end
end

app/controllers/wholeseller/payments_controller.rb
class Wholeseller::PaymentsController < ApplicationController
  before_filter :authenticate_user!
  layout "wholeseller"

  def confirm_payment
    @payment = Payment.new
  end

  def save_confirm_payment
    @payment = Payment.new(params[:payment])
    respond_to do |format|
      if @payment.save
        format.html { redirect_to wholeseller_dashboards_url, notice: 'Konfirmasi payment berhasil.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "confirm_payment" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/seller/posts_helper.rb
module Seller::PostsHelper
end

app/helpers/wholeseller/bergains_helper.rb
module Wholeseller::BergainsHelper
end

app/helpers/wholeseller/orders_helper.rb
module Wholeseller::OrdersHelper
end

app/helpers/wholeseller/payments_helper.rb
module Wholeseller::PaymentsHelper
end

app/helpers/wholeseller/posts_helper.rb
module Wholeseller::PostsHelper
end

app/views/wholeseller/posts/_form.html.erb
<%= form_for(post, url: url, html: {method: method, multipart: true}, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this wholeseller_bergain from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :selling_price, "Harga Jual", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :selling_price, :class => "form-control", :placeholder => "Harga Jual Per kilogram Untuk Pembeli" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wholeseller/posts/berganing_product_price.html.erb
<h1>Menentukan Tanggal Survey dan Penawaran</h1>

<table>
  <tr>
    <th>Judul Post</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><%= @order.post.title rescue "-" %></td>
    <td><%= @order.quantity %></td>
  </tr>
</table>
<br/>
<br/>
<br/>
<hr></hr>
<%= form_for(@bergain, :url => save_berganing_wholeseller_posts_path, :method => 'post') do |f| %>
  <% if @bergain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bergain.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @bergain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_date, "Tanggal Survey" %>*<br />
    <%= f.date_select :survey_date %>
  </div>
  <div class="field">
    <%= f.label :bergain_price, "Harga Penawaran" %><br />
    <%= f.number_field :bergain_price %>
  </div>
  <div class="actions">
    <%= f.submit "Finish" %>
  </div>
<% end %>

app/views/wholeseller/posts/edit.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <%= link_to 'Back', my_post_wholeseller_posts_path, :class => "btn btn-primary" %>
</div>

<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Mengubah post</h3>
    </div>
    <div class="panel-body">
      <%= render "form", url: wholeseller_post_path(@post), method: 'put', post: @post %>
    </div>
  </div>
</div>

app/views/wholeseller/posts/finish_bergaining.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Ringkasan akhir Penawaran</h3>
    </div>
    <div class="panel-body">
      <p>
        <b>Judul Post:</b>
        <%= @order.post.title rescue "-" %>
      </p>
      <p>
        <b>Harga penawaran perkilogram: </b>
        <%= @bergain.bergain_price rescue "-" %>
      </p>
      <p>
        <b>Tanggal survey </b>
        <%= @bergain.survey_date rescue "-" %>
      </p>
    </div>
  </div>
</div>

app/views/wholeseller/posts/index.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <%= link_to "Mengelola Post Saya", my_post_wholeseller_posts_path, :class => "btn btn-primary" %>
</div>

<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Daftar Post</h3>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th>Photo</th>
            <th>Judul</th>
            <th>Deskripsi</th>
            <th>Tanggal Panen</th>
            <th>Quantity</th>
            <th>Harga beli</th>
            <th>Satuan</th>
            <th>Nama Penjual</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each_with_index do |post, idx| %>
            <tr>
              <td><%= idx + 1 %></td>
              <td>
                <%= image_tag(post.photo_image_url(:thumb)) if post.photo_image? %>
                <%= image_tag("/assets/160x120.gif", :width => "200") if post.photo_image.blank? %>
              </td>
              <td><%= post.title %></td>
              <td><%= post.description %></td>
              <td><%= post.harvest_date %></td>
              <td><%= post.quantity %></td>
              <td><%= post.purchase_price %></td>
              <td>Kg</td>
              <td><%= post.user.name rescue "-" %></td>
              <td><%= link_to 'Show', wholeseller_post_path(post), :class => "btn btn-link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/wholeseller/posts/my_post.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Daftar Post Saya</h3>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th>Judul</th>
            <th>Nama Petani</th>
            <th>Harga Jual Ke Pembeli</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each_with_index do |post, idx| %>
            <tr>
              <td><%= idx + 1 %></td>
              <td><%= post.title %></td>
              <td><%= post.user.name rescue "-" %></td>
              <td><%= post.selling_price rescue "-" %></td>
              <td><%= link_to 'Edit', edit_wholeseller_post_path(post), :class => "btn btn-link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/wholeseller/posts/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <%= link_to 'Back', wholeseller_posts_path, :class => "btn btn-primary" %>
</div>
<div class="col-xs-12 col-sm-6 col-md-9"></div>

<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Langkah 1 Membuat jadwal survey</h3>
    </div>
    <div class="panel-body">
      <p>
        <b>Judul:</b>
        <%= @post.title %>
      </p>

      <p>
        <b>Deskripsi:</b>
        <%= @post.description %>
      </p>

      <p>
        <b>Tanggal Panen:</b>
        <%= @post.harvest_date %>
      </p>

      <p>
        <b>Quantity:</b>
        <%= @post.quantity %>
      </p>

      <p>
        <b>Photo:</b>
        <%= image_tag(@post.photo_image_url(:thumb)) if @post.photo_image? %>
      </p>

      <%= form_for(@bergain, :url => save_berganing_wholeseller_posts_path, :method => 'post') do |f| %>
        <% if @bergain.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@bergain.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
              <% @bergain.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :survey_date, "Tanggal Survey" %><br />
          <%= f.date_select :survey_date %>
          <%= f.hidden_field :post_id, :value => @post.id %>
        </div>
        <div class="field">
          <%= f.label :bergain_price, "Harga Penawaran per kilogram" %><br />
          <%= f.number_field :bergain_price %>
        </div>
        <div class="actions">
          <%= f.submit "Finish" %>
        </div>
      <% end %>
    </div>
  </div>
</div>