config/routes.rb
Hasilsda::Application.routes.draw do
  devise_for :users

  resources :payments

  resources :bergains

  resources :orders

  resources :posts

  resources :users

  namespace :admin do
    resources :dashboards, :only => [:index]
    resources :users
    resources :payments
  end

  namespace :seller do
    resources :dashboards
    resources :posts
    resources :bergains
    resources :orders
  end

  namespace :wholeseller do
    resources :dashboards
    resources :posts do
      collection do
        get :berganing_product_price
        get :finish_transaction
        get :finish_bergaining
        get :my_post
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  namespace :buyer do
    resources :dashboards
    resources :posts do
      collection do
        get :finish_transaction
        post :save_berganing
      end
    end
    resources :bergains
    resources :payments do
      collection do
        get :confirm_payment
        post :save_confirm_payment
      end
    end
    resources :orders do
      member do
        get :add_order
        get :method_payment
        get :finish_transaction
        put :update_method_payment
        post :add_to_order
      end
    end
    resources :bergains
  end

  resources :home do
    collection do
      get :search
      get :about
    end
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :name, :status_user, :total_deposit, :type_user, :username,
    :address, :regency

  has_many :posts
  has_many :orders

  validates :name, :presence => true
  validates :type_user, :presence => true

  TYPES_USER = ["Seller", "Wholeseller", "Buyer"]

  def is_seller?
    self.type_user == "Seller"
  end

  def is_wholeseller?
    self.type_user == "Wholeseller"
  end

  def is_buyer?
    self.type_user == "Buyer"
  end

  def is_admin?
    self.type_user == "Admin"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  layout "admin"

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.where(["type_user != ?", "Admin"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:admin_user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:admin_user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user, url: url, html: {method: method, multipart: true}) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>

<%= render "form", url: admin_user_path(@user), method: 'put', bergain: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <%= link_to 'New User', new_admin_user_path, :class => "btn btn-primary" %>
</div>
<div class="col-xs-12 col-sm-6 col-md-9"></div>
<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Daftar User</h3>
    </div>
    <div class="panel-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Type user</th>
            <th>Total deposit</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each_with_index do |user, idx| %>
            <tr>
              <td><%= idx + 1 %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= user.type_user %></td>
              <td><%= user.total_deposit %></td>
              <td>
                <%= link_to 'Show', admin_user_path(user), :class => "btn btn-link" %>
                <%#= link_to 'Edit', edit_admin_user_path(user), :class => "btn btn-link" %>
                <%#= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>New admin_user</h1>

<%= render 'form', url: admin_users_path, method: 'post' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-9">
  <%= link_to 'Back', admin_users_path, :class => "btn btn-primary" %>
</div>
<div class="col-xs-12 col-sm-6 col-md-9"></div>
<div class="col-xs-12 col-sm-6 col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Melihat user</h3>
    </div>
    <div class="panel-body">
      <p>
        <b>Nama:</b>
        <%= @user.name %>
      </p>

      <p>
        <b>Email:</b>
        <%= @user.email %>
      </p>

      <p>
        <b>Type User:</b>
        <%= @user.type_user %>
      </p>

      <p>
        <b>Total Deposit:</b>
        <%= @user.total_deposit %>
      </p>
    </div>
  </div>
</div>